#!/usr/bin/env bash

for pid in /proc/*/; do
    pid=${pid%*/}
    pid=${pid##*/}
    
    if [[ $pid =~ ^[0-9]+$ ]]; then
	    command_name=$(tr -d '\0' < "/proc/$pid/cmdline")
	    if [[ $command_name == *"bash"* ]]; then
		    echo "$pid $command_name"
        fi
    fi
done
