#!/usr/bin/env bash

case "$1" in
	start)
		if [ -f /var/run/my_process.pid ]; then
			exit 1
		fi

		echo $$ > /var/run/my_process.pid
		echo "manage_my_process started"


		while true; do
			echo "I am alive!" >> /tmp/my_process
			sleep 2
		done
		;;
	stop)
		if [ ! -f /var/run/my_process.pid ]; then
			exit 1
		fi

		pd=$(cat /var/run/my_process.pid)
		rm /var/run/my_process.pid
		echo "manage_my_process stopped"
		kill $pd
		;;
	restart)
		$0 stop
		$0 start
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac


























