#!/usr/bin/env bash
#This script that displays the content of the file /etc/passwd

fl="/etc/passwd"

while IFS=':' read -r username _ uid gid user_info home shell; do
	read -r ___ password _ < <(grep "^${username}:" /etc/shadow)
	echo "The user $username is part of the $gid gang, lives in $home and rides $shell."
	echo "USER ID's place is protected by the passcode $password."
	echo "More info about the user here: $user_info."
done < "$fl"
