#!/usr/bin/env bash
#This script displays visitor ip along http status code from the apache log file

log_fl="apache-access.log"

awk '{counter[$1" "$9]++} END {for (key in counter) print counter[key], key}' "$log_fl" | sort -rn 
