#!/usr/bin/env bash
#The script below is display clock
hour=0
min=1

while [ $hour -le 13 ]; do
	printf "Hour: %d\n" $hour
	while [ $min -lt 60 ]; do
		echo $min
		((min++))
	done
	((hour++))
	min=1
done
